services:
  db-minipp:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    network_mode: bridge
    volumes:
      - db-minipp:/var/lib/postgresql/data
    extra_hosts:
      - host.docker.internal:host-gateway

volumes:
  db-minipp: